# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: SearchAccountByName.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'SearchAccountByName.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from Proto.compiled import PlayerPersonalShow_pb2 as PlayerPersonalShow__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19SearchAccountByName.proto\x12\x13SearchAccountByName\x1a\x18PlayerPersonalShow.proto\"\x1a\n\x07request\x12\x0f\n\x07keyword\x18\x01 \x01(\t\"?\n\x08response\x12\x33\n\x05infos\x18\x01 \x03(\x0b\x32$.PlayerPersonalShow.AccountInfoBasicb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SearchAccountByName_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REQUEST']._serialized_start=76
  _globals['_REQUEST']._serialized_end=102
  _globals['_RESPONSE']._serialized_start=104
  _globals['_RESPONSE']._serialized_end=167
# @@protoc_insertion_point(module_scope)
